In [1]:
%%writefile new.py                         # create file and write method in it 
def do (x) :
    return (num for num in range(x) if num%2 ==0 )

Writing new.py


In [5]:
# to use the function do 
from new import do 
x = do(30)
print(list(x))

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28]


In [11]:
# How to pass an argument to a file  (argument be sent to the system package which has argv)
%%writefile new.py    
import sys 
x = int(sys.argv[1])
print ([num for num in range(x) if num%2==0])


UsageError: Line magic function `%%writefile` not found.


In [12]:
! python new.py 100 

In [13]:
import numpy as np 
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.linspace(0,9,10)    # print numbers with equal spaces 

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [34]:
num = np.random.randint(0,10,(4,4))     


In [36]:
np.split(num,num.shape[0])

[array([[7, 6, 2, 9]]),
 array([[1, 8, 4, 2]]),
 array([[4, 1, 4, 0]]),
 array([[4, 0, 7, 5]])]

In [28]:
num[:2,-2:]

array([[5, 7],
       [8, 7]])

In [30]:
ind = ((2,3),(2))
num[ind]

array([4, 8])

In [21]:
np.random.random((4,4))      # random numbers (normal distriution )

array([[0.05049921, 0.35738563, 0.48522866, 0.77580347],
       [0.25472549, 0.23663834, 0.15471382, 0.13294698],
       [0.50633591, 0.55504518, 0.61507083, 0.69370233],
       [0.92480144, 0.27729909, 0.95711755, 0.21316143]])

In [24]:
a = np.array([1,2,3,4,5])
a = np.append(a,6)
a

array([1, 2, 3, 4, 5, 6])

In [31]:
np.power(a,2)

array([ 1,  4,  9, 16, 25, 36], dtype=int32)

In [32]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ])

In [33]:
np.multiply(a,4)

array([ 4,  8, 12, 16, 20, 24])

In [40]:
a = np.array([1,2,3,4])
a.shape          # vector 

(4,)

In [41]:
a = a[:,np.newaxis ]
a.shape

(4, 1)

In [46]:
num = np.random.randint(0,10,(4,4))     
num[num>1]
num[(num > 1) & (num<4)]


array([2])

In [47]:
np.sort(num , axis = 0)

array([[1, 5, 0, 0],
       [1, 6, 5, 1],
       [2, 7, 5, 6],
       [4, 9, 8, 8]])

In [48]:
np.sort(num , axis = 1)

array([[2, 5, 8, 9],
       [1, 1, 7, 8],
       [4, 5, 5, 6],
       [0, 0, 1, 6]])

In [49]:
np.min(num , axis = 0)

array([1, 5, 0, 0])

In [52]:
import pandas as pd 
friends = {
    "name" : ["hanem" , "salma " , "alaa"]
   , "age":[20,22,23]
}
df = pd.DataFrame(friends)
df 

name  age
0   hanem   20
1  salma    22
2    alaa   23

In [57]:
friends = [["alaa" , 22] ,["salma" ,23] , ["aliaa" ,25]]
df = pd.DataFrame(friends)
df.columns = ["name" , "age"]
df

name  age
0   alaa   22
1  salma   23
2  aliaa   25

In [59]:
data = pd.read_csv(r"G:\Eng. Ahmed Rady\machine_lectures\12\task.csv")
data[1:3]

date      price  bedrooms  bathrooms  sqft_living  sqft_lot  \
1  5/2/2014 0:00  2384000.0       5.0        2.5       3650.0    9050.0   
2  5/2/2014 0:00   342000.0       3.0        2.0       1930.0   11947.0   

   floors  waterfront  view  condition  sqft_above  sqft_basement  yr_built  \
1     2.0         0.0   4.0        5.0      3370.0          280.0    1921.0   
2     1.0         0.0   0.0        4.0      1930.0            0.0    1966.0   

   yr_renovated                    street     city  statezip country  
1           0.0           709 W Blaine St  Seattle  WA 98119     USA  
2           0.0  26206-26214 143rd Ave SE     Kent  WA 98042     USA

In [60]:
data.loc[1:3]

date      price  bedrooms  bathrooms  sqft_living  sqft_lot  \
1  5/2/2014 0:00  2384000.0       5.0       2.50       3650.0    9050.0   
2  5/2/2014 0:00   342000.0       3.0       2.00       1930.0   11947.0   
3  5/2/2014 0:00   420000.0       3.0       2.25       2000.0    8030.0   

   floors  waterfront  view  condition  sqft_above  sqft_basement  yr_built  \
1     2.0         0.0   4.0        5.0      3370.0          280.0    1921.0   
2     1.0         0.0   0.0        4.0      1930.0            0.0    1966.0   
3     1.0         0.0   0.0        4.0      1000.0         1000.0    1963.0   

   yr_renovated                    street      city  statezip country  
1           0.0           709 W Blaine St   Seattle  WA 98119     USA  
2           0.0  26206-26214 143rd Ave SE      Kent  WA 98042     USA  
3           0.0           857 170th Pl NE  Bellevue  WA 98008     USA

In [62]:
data.loc[1:3,["price" ,"floors"]]

price  floors
1  2384000.0     2.0
2   342000.0     1.0
3   420000.0     1.0

In [64]:
data.iloc[1:4,[0,2]]   # integer loc (slice)

date  bedrooms
1  5/2/2014 0:00       5.0
2  5/2/2014 0:00       3.0
3  5/2/2014 0:00       3.0

In [65]:
data.loc[[1,3]]      # select rows

date      price  bedrooms  bathrooms  sqft_living  sqft_lot  \
1  5/2/2014 0:00  2384000.0       5.0       2.50       3650.0    9050.0   
3  5/2/2014 0:00   420000.0       3.0       2.25       2000.0    8030.0   

   floors  waterfront  view  condition  sqft_above  sqft_basement  yr_built  \
1     2.0         0.0   4.0        5.0      3370.0          280.0    1921.0   
3     1.0         0.0   0.0        4.0      1000.0         1000.0    1963.0   

   yr_renovated           street      city  statezip country  
1           0.0  709 W Blaine St   Seattle  WA 98119     USA  
3           0.0  857 170th Pl NE  Bellevue  WA 98008     USA

In [66]:
data.head(10)

date      price  bedrooms  bathrooms  sqft_living  sqft_lot  \
0  5/2/2014 0:00   313000.0       3.0       1.50       1340.0    7912.0   
1  5/2/2014 0:00  2384000.0       5.0       2.50       3650.0    9050.0   
2  5/2/2014 0:00   342000.0       3.0       2.00       1930.0   11947.0   
3  5/2/2014 0:00   420000.0       3.0       2.25       2000.0    8030.0   
4  5/2/2014 0:00   550000.0       4.0       2.50       1940.0   10500.0   
5  5/2/2014 0:00   490000.0       2.0       1.00        880.0    6380.0   
6  5/2/2014 0:00   335000.0       2.0       2.00       1350.0    2560.0   
7  5/2/2014 0:00   482000.0       4.0       2.50       2710.0   35868.0   
8  5/2/2014 0:00   452500.0       3.0       2.50       2430.0   88426.0   
9  5/2/2014 0:00   640000.0       4.0       2.00       1520.0    6200.0   

   floors  waterfront  view  condition  sqft_above  sqft_basement  yr_built  \
0     1.5         0.0   0.0        3.0      1340.0            0.0    1955.0   
1     2.0         0.0   4.0        5.0      3370.0          280.0    1921.0   
2     1.0         0.0   0.0        4.0      1930.0            0.0    1966.0   
3     1.0         0.0   0.0        4.0      1000.0         1000.0    1963.0   
4     1.0         0.0   0.0        4.0      1140.0          800.0    1976.0   
5     1.0         0.0   0.0        3.0       880.0            0.0    1938.0   
6     1.0         0.0   0.0        3.0      1350.0            0.0    1976.0   
7     2.0         0.0   0.0        3.0      2710.0            0.0    1989.0   
8     1.0         0.0   0.0        4.0      1570.0          860.0    1985.0   
9     1.5         0.0   0.0        3.0      1520.0            0.0    1945.0   

   yr_renovated                    street          city  statezip country  
0        2005.0      18810 Densmore Ave N     Shoreline  WA 98133     USA  
1           0.0           709 W Blaine St       Seattle  WA 98119     USA  
2           0.0  26206-26214 143rd Ave SE          Kent  WA 98042     USA  
3           0.0           857 170th Pl NE      Bellevue  WA 98008     USA  
4        1992.0         9105 170th Ave NE       Redmond  WA 98052     USA  
5        1994.0            522 NE 88th St       Seattle  WA 98115     USA  
6           0.0         2616 174th Ave NE       Redmond  WA 98052     USA  
7           0.0         23762 SE 253rd Pl  Maple Valley  WA 98038     USA  
8           0.0   46611-46625 SE 129th St    North Bend  WA 98045     USA  
9        2010.0          6811 55th Ave NE       Seattle  WA 98115     USA

In [67]:
data.tail(5)

date        price  bedrooms  bathrooms  sqft_living  sqft_lot  \
4595   7/9/2014 0:00  308166.6667       3.0       1.75       1510.0    6360.0   
4596   7/9/2014 0:00  534333.3333       3.0       2.50       1460.0    7573.0   
4597   7/9/2014 0:00  416904.1667       3.0       2.50       3010.0    7014.0   
4598  7/10/2014 0:00  203400.0000       4.0       2.00       2090.0    6630.0   
4599  7/10/2014 0:00  220600.0000       3.0       2.50       1490.0    8102.0   

      floors  waterfront  view  condition  sqft_above  sqft_basement  \
4595     1.0         0.0   0.0        4.0      1510.0            0.0   
4596     2.0         0.0   0.0        3.0      1460.0            0.0   
4597     2.0         0.0   0.0        3.0      3010.0            0.0   
4598     1.0         0.0   0.0        3.0      1070.0         1020.0   
4599     2.0         0.0   0.0        4.0      1490.0            0.0   

      yr_built  yr_renovated             street       city  statezip country  
4595    1954.0        1979.0     501 N 143rd St    Seattle  WA 98133     USA  
4596    1983.0        2009.0   14855 SE 10th Pl   Bellevue  WA 98007     USA  
4597    2009.0           0.0   759 Ilwaco Pl NE     Renton  WA 98059     USA  
4598    1974.0           0.0  5148 S Creston St    Seattle  WA 98178     USA  
4599    1990.0           0.0  18717 SE 258th St  Covington  WA 98042     USA

In [70]:
data [data["city"] == "Seattle"]

date         price  bedrooms  bathrooms  sqft_living  \
1      5/2/2014 0:00  2.384000e+06       5.0       2.50       3650.0   
5      5/2/2014 0:00  4.900000e+05       2.0       1.00        880.0   
9      5/2/2014 0:00  6.400000e+05       4.0       2.00       1520.0   
11     5/2/2014 0:00  1.400000e+06       4.0       2.50       2920.0   
13     5/2/2014 0:00  3.650000e+05       3.0       1.00       1090.0   
...              ...           ...       ...        ...          ...   
4582   7/7/2014 0:00  4.060625e+05       2.0       1.00       1290.0   
4585   7/7/2014 0:00  4.868950e+05       3.0       1.00       1890.0   
4591   7/8/2014 0:00  3.961667e+05       3.0       1.75       1880.0   
4595   7/9/2014 0:00  3.081667e+05       3.0       1.75       1510.0   
4598  7/10/2014 0:00  2.034000e+05       4.0       2.00       2090.0   

      sqft_lot  floors  waterfront  view  condition  sqft_above  \
1       9050.0     2.0         0.0   4.0        5.0      3370.0   
5       6380.0     1.0         0.0   0.0        3.0       880.0   
9       6200.0     1.5         0.0   0.0        3.0      1520.0   
11      4000.0     1.5         0.0   0.0        5.0      1910.0   
13      6435.0     1.0         0.0   0.0        4.0      1090.0   
...        ...     ...         ...   ...        ...         ...   
4582    4650.0     1.0         0.0   0.0        4.0      1290.0   
4585    3330.0     1.5         0.0   0.0        4.0      1390.0   
4591    5752.0     1.0         0.0   0.0        4.0       940.0   
4595    6360.0     1.0         0.0   0.0        4.0      1510.0   
4598    6630.0     1.0         0.0   0.0        3.0      1070.0   

      sqft_basement  yr_built  yr_renovated                 street     city  \
1             280.0    1921.0           0.0        709 W Blaine St  Seattle   
5               0.0    1938.0        1994.0         522 NE 88th St  Seattle   
9               0.0    1945.0        2010.0       6811 55th Ave NE  Seattle   
11           1010.0    1909.0        1988.0  3838-4098 44th Ave NE  Seattle   
13              0.0    1955.0        2009.0    2504 SW Portland Ct  Seattle   
...             ...       ...           ...                    ...      ...   
4582            0.0    1906.0        1990.0         312 NE 81st St  Seattle   
4585          500.0    1901.0           0.0      4324 Dayton Ave N  Seattle   
4591          940.0    1945.0           0.0     3529 SW Webster St  Seattle   
4595            0.0    1954.0        1979.0         501 N 143rd St  Seattle   
4598         1020.0    1974.0           0.0      5148 S Creston St  Seattle   

      statezip country  
1     WA 98119     USA  
5     WA 98115     USA  
9     WA 98115     USA  
11    WA 98105     USA  
13    WA 98106     USA  
...        ...     ...  
4582  WA 98115     USA  
4585  WA 98103     USA  
4591  WA 98126     USA  
4595  WA 98133     USA  
4598  WA 98178     USA  

[1573 rows x 18 columns]

In [71]:
data.filter(like="s" , axis = 1 )      # take columns which have char s only 

bedrooms  bathrooms  sqft_living  sqft_lot  floors  sqft_above  \
0          3.0       1.50       1340.0    7912.0     1.5      1340.0   
1          5.0       2.50       3650.0    9050.0     2.0      3370.0   
2          3.0       2.00       1930.0   11947.0     1.0      1930.0   
3          3.0       2.25       2000.0    8030.0     1.0      1000.0   
4          4.0       2.50       1940.0   10500.0     1.0      1140.0   
...        ...        ...          ...       ...     ...         ...   
4595       3.0       1.75       1510.0    6360.0     1.0      1510.0   
4596       3.0       2.50       1460.0    7573.0     2.0      1460.0   
4597       3.0       2.50       3010.0    7014.0     2.0      3010.0   
4598       4.0       2.00       2090.0    6630.0     1.0      1070.0   
4599       3.0       2.50       1490.0    8102.0     2.0      1490.0   

      sqft_basement                    street  statezip  
0               0.0      18810 Densmore Ave N  WA 98133  
1             280.0           709 W Blaine St  WA 98119  
2               0.0  26206-26214 143rd Ave SE  WA 98042  
3            1000.0           857 170th Pl NE  WA 98008  
4             800.0         9105 170th Ave NE  WA 98052  
...             ...                       ...       ...  
4595            0.0            501 N 143rd St  WA 98133  
4596            0.0          14855 SE 10th Pl  WA 98007  
4597            0.0          759 Ilwaco Pl NE  WA 98059  
4598         1020.0         5148 S Creston St  WA 98178  
4599            0.0         18717 SE 258th St  WA 98042  

[4600 rows x 9 columns]

In [72]:
data.drop([1,2], inplace=True)    # drop raws 

date        price  bedrooms  bathrooms  sqft_living  sqft_lot  \
0      5/2/2014 0:00  313000.0000       3.0       1.50       1340.0    7912.0   
3      5/2/2014 0:00  420000.0000       3.0       2.25       2000.0    8030.0   
4      5/2/2014 0:00  550000.0000       4.0       2.50       1940.0   10500.0   
5      5/2/2014 0:00  490000.0000       2.0       1.00        880.0    6380.0   
6      5/2/2014 0:00  335000.0000       2.0       2.00       1350.0    2560.0   
...              ...          ...       ...        ...          ...       ...   
4595   7/9/2014 0:00  308166.6667       3.0       1.75       1510.0    6360.0   
4596   7/9/2014 0:00  534333.3333       3.0       2.50       1460.0    7573.0   
4597   7/9/2014 0:00  416904.1667       3.0       2.50       3010.0    7014.0   
4598  7/10/2014 0:00  203400.0000       4.0       2.00       2090.0    6630.0   
4599  7/10/2014 0:00  220600.0000       3.0       2.50       1490.0    8102.0   

      floors  waterfront  view  condition  sqft_above  sqft_basement  \
0        1.5         0.0   0.0        3.0      1340.0            0.0   
3        1.0         0.0   0.0        4.0      1000.0         1000.0   
4        1.0         0.0   0.0        4.0      1140.0          800.0   
5        1.0         0.0   0.0        3.0       880.0            0.0   
6        1.0         0.0   0.0        3.0      1350.0            0.0   
...      ...         ...   ...        ...         ...            ...   
4595     1.0         0.0   0.0        4.0      1510.0            0.0   
4596     2.0         0.0   0.0        3.0      1460.0            0.0   
4597     2.0         0.0   0.0        3.0      3010.0            0.0   
4598     1.0         0.0   0.0        3.0      1070.0         1020.0   
4599     2.0         0.0   0.0        4.0      1490.0            0.0   

      yr_built  yr_renovated                street       city  statezip  \
0       1955.0        2005.0  18810 Densmore Ave N  Shoreline  WA 98133   
3       1963.0           0.0       857 170th Pl NE   Bellevue  WA 98008   
4       1976.0        1992.0     9105 170th Ave NE    Redmond  WA 98052   
5       1938.0        1994.0        522 NE 88th St    Seattle  WA 98115   
6       1976.0           0.0     2616 174th Ave NE    Redmond  WA 98052   
...        ...           ...                   ...        ...       ...   
4595    1954.0        1979.0        501 N 143rd St    Seattle  WA 98133   
4596    1983.0        2009.0      14855 SE 10th Pl   Bellevue  WA 98007   
4597    2009.0           0.0      759 Ilwaco Pl NE     Renton  WA 98059   
4598    1974.0           0.0     5148 S Creston St    Seattle  WA 98178   
4599    1990.0           0.0     18717 SE 258th St  Covington  WA 98042   

     country  
0        USA  
3        USA  
4        USA  
5        USA  
6        USA  
...      ...  
4595     USA  
4596     USA  
4597     USA  
4598     USA  
4599     USA  

[4598 rows x 18 columns]

In [74]:
def map (raw) :
    if raw == 0.0 :
      return False
    else :
       return False

In [76]:
data ["view"] = data ["view"].apply(map)
data ["view"]

0       False
1       False
2       False
3       False
4       False
        ...  
4595    False
4596    False
4597    False
4598    False
4599    False
Name: view, Length: 4600, dtype: bool

In [77]:
data.duplicated("view")

0       False
1        True
2        True
3        True
4        True
        ...  
4595     True
4596     True
4597     True
4598     True
4599     True
Length: 4600, dtype: bool

In [78]:
test = data.drop_duplicates(["view"])
test

date     price  bedrooms  bathrooms  sqft_living  sqft_lot  \
0  5/2/2014 0:00  313000.0       3.0        1.5       1340.0    7912.0   

   floors  waterfront   view  condition  sqft_above  sqft_basement  yr_built  \
0     1.5         0.0  False        3.0      1340.0            0.0    1955.0   

   yr_renovated                street       city  statezip country  
0        2005.0  18810 Densmore Ave N  Shoreline  WA 98133     USA

In [83]:
import os 
os.getcwd()   # to know the current path 

'f:\\conda_projects'

In [84]:
os.listdir()     # to know files in the current path

['Decorators.ipynb',
 'multiple_linear_regression with accurecy.ipynb',
 'multiple_linear_regression.ipynb',
 'multiple_linear_regression_with sklearn.ipynb',
 'new.py',
 'Packages&Files.ipynb',
 'project1',
 'simple regression.ipynb',
 '__pycache__']

In [ ]:
# os.chdir(" path") >> (change the path )

In [86]:
os.chdir('..')            # out 
os.listdir()

['$RECYCLE.BIN',
 'conda_projects',
 'Download',
 'Git-2.41.0.3-64-bit.exe',
 'System Volume Information',
 'امى']

In [ ]:
import sys
sys.path.append('..')        # run file without going to it 
# import (file_name)